# Generated by Django 4.0.2 on 2022-03-29 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('link_repository', models.URLField(verbose_name='Репо')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'project_list',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_note', models.TextField(blank=True, null=True, verbose_name='Текст заметки')),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Создано')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name='Обновлено')),
                ('status', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'db_table': 'todo_list',
            },
        ),
    ]
